aprocess.out:aprocess.c bprocess.c
	gcc aprocess.c -o aprocess.out
	gcc bprocess.c -o bprocess.out
	gcc a1process.c -o a1process.out
	gcc b1process.c -o b1process.out
.PHONY:clean
clean:
	rm aprocess.out bprocess.out a1process.out b1process.out
